### ISSUE TITLE
Inference ErrorCannot find class R on compile

### ISSUE THREAD

**Issue by xinuc** [mirah/pindah#8]
I always get error like this when trying to compile a newly generated project:

<pre>
compile:
Inference Error:
./org/xinuc/bukalapak/Start.mirah:6: Cannot find class R
    setContentView R.layout.main
                  ^^
rake aborted!
org.apache.tools.ant.BuildException: exec returned: 1
</pre>

how can I fix this?

**Comment by zapnap** [comment]
Can you confirm that you're using the latest master? Or gem version?

**Comment by xinuc** [comment]
Yup, I'm using the latest master

**Comment by xinuc** [comment]
Here is what I do to reproduce the error:

<pre>
$ git clone https://github.com/mirah/pindah.git
$ pindah/bin/pindah create org.xinuc.pindahtest pindahtest Start
$ cd pindahtest
</pre>

edit Rakefile, replace

<pre>
require "rubygems"
require "pindah"
</pre>

with

<pre>
require "../pindah/lib/pindah"
</pre>


then run `rake compile`

**Comment by technomancy** [comment]
I just pushed a fix to git master that should take care of this; please reopen if it persists.

**Comment by xinuc** [comment]
Hi, I can confirm that this issue persists.

**Comment by xinuc** [comment]
Actually I can run `rake debug` and even `rake install` and I got my project installed (but can't be run). The error still persists.

**Comment by zapnap** [comment]
Can you try my fork (zapnap/pindah)?

**Comment by xinuc** [comment]
Nope, still no luck with your fork too.. :(

**Comment by technomancy** [comment]
Can anyone else confirm this? I can't repro. Maybe it has to do with the version of JRuby used? Upgrading to the latest RC may help.

**Comment by zapnap** [comment]
I was able to reproduce when running rake compile on current master. But I can't seem to replicate it on my own fork (slightly behind). Haven't yet had time to dig in any deeper though.

**Comment by zapnap** [comment]
using jruby 1.5.2 fwiw

**Comment by xinuc** [comment]
OK, I don't know what's going on...
I've updated my jruby and mirah

<pre>
$ ruby -v
jruby 1.6.0.RC2 (ruby 1.8.7 patchlevel 330) (2011-02-09 5434c72) (OpenJDK Client VM 1.6.0_20) [linux-i386-java]
</pre>

<pre>
$ mirahc -v
Mirah v0.0.6.dev
</pre>


and run the exact steps I described [above](https://github.com/mirah/pindah/issues/8/#issue/8/comment/786587)
is there any problem with this steps?

I still got this error:

<pre>
compile:
compiling Duby source in /home/xinuc/sandbox/pindahtest/src to /home/xinuc/sandbox/pindahtest/bin/classes
Inference Error:
/home/xinuc/sandbox/pindahtest/src/org/xinuc/pindahtest/Start.mirah:6: Cannot find class R
    setContentView R.layout.main
                  ^^
</pre>

What else can be wrong?

**Comment by technomancy** [comment]
The new "pindah create" skeleton puts in an explicit package declaration since someone else realized this fixed the problem on their machine. Does it solve it for you as well?

**Comment by xinuc** [comment]
Actually no. Still the same error.

Do you have a clue why this happen in my env?
A quick fix or a hack to fix this in my own laptop will be fine.

**Comment by teemun** [comment]
I ran into same issue. What helped, was the combination of an explicit package declaration and small modification to pindah build.xml.

Declared:

```
<path id="java.classpath">
    <pathelement location="${classpath}" />
</path>
```

And modified compile target:

```
<mirahc src="${src}" destdir="${classes}">  
    <classpath refid="java.classpath" />
</mirahc>
```

**Comment by xinuc** [comment]
@teemun thanks a lot...
Finally I can compile it without any error...

@technomancy is there any chance this modification pulled into pindah?

**Comment by xinuc** [comment]
created pull request here https://github.com/mirah/pindah/pull/14 in case you're interested.

got 2 failed tests, but they're there before this modification.

**Comment by mkilling** [comment]
Still happens for me with current master.
